[build-system]
requires = ["setuptools<60"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ['py36', 'py37', 'py38', 'py39', 'py310']

[tool.isort]
profile = "black"
multi_line_output = 3
py_version = 36
