[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ['py36']

[tool.isort]
profile = "black"
multi_line_output = 3
py_version = 36
