/* Generated by Cython 0.29.32 */

#ifndef __PYX_HAVE__matrix_multiply_lico__matmul_print
#define __PYX_HAVE__matrix_multiply_lico__matmul_print

#include "Python.h"

#ifndef __PYX_HAVE_API__matrix_multiply_lico__matmul_print

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C sigset_t exitMask;

#endif /* !__PYX_HAVE_API__matrix_multiply_lico__matmul_print */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initmatmul_print(void);
#else
PyMODINIT_FUNC PyInit_matmul_print(void);
#endif

#endif /* !__PYX_HAVE__matrix_multiply_lico__matmul_print */
